Customise alarm panel topic
vanackej/risco-mqtt-local pull request #37
Opened 2022-05-25 15:49 UTC by markxroberts

Updated in typescript
Two additional configs added:
risco_alarm_topic
risco_node_id
These permit multiple panels to be configured.
Rearrangement of mqtt config options so that risco_alarm_topic is used for will.
Regex entries amended to permit custom topic
Addresses issue #33 by permitting multiple panels, but does not link panels.

2022-06-29 20:42 UTC, vanackej commented on README.md
> +  "mqtt_alarm_topic": "riscopanel" //Optional - topic to which state changes are published
Wouldn't it be possible to simply use the risco_node_id property to automatically compute the mqtt_alarm_topic ? It would simplify the configuration

2022-06-29 20:47 UTC, vanackej requested changes
Excepted the comment regarding the simplification of the configuration (by removing explicit mqtt_alarm_topic configuraiton option), seems fine to me

2022-06-30 07:11 UTC, markxroberts commented
Agree that would be simpler to have only one configuration option.  I made them different as I wasn't sure whether there was a reason that they had been defined differently.  Do we need to make the MQTT alarm topic different to the risco-node-id, or could they just be the same?

2022-07-01 19:52 UTC, markxroberts commented
I'll update my comment above by saying that this change causes significant problems for me.  HA tries to duplicate the entities.  I can't work out whether this will be a problem for others, but I suspect it will.  I wonder whether we ought to offer a configuration option for the alarm panel topic and name as we do for the sensors.  This would help to mitigate this problem.

2022-07-01 19:54 UTC, markxroberts commented on README.md
> +  "mqtt_alarm_topic": "riscopanel" //Optional - topic to which state changes are published
Change made, but see my later comments

2022-07-04 07:33 UTC, vanackej commented
Hi
I want to be able to review and integrate the various features one by one.
Last week I cleaned up your work regarding multiple panels support and made some internal code style improvement (style, topics names, ...) : https://github.com/vanackej/risco-mqtt-local/tree/feature/support_multiple_panels

Can you please clean up the git history in your branches and make one commit per feature please ? It would be easier to review and integrate for me

2022-07-04 16:01 UTC, markxroberts commented
Sure.  If I make any further contributions, I'll be sure to follow that.  To be honest, you're much better at this than me, so I don't think I've got much to offer now.

2022-07-04 16:12 UTC, vanackej commented
Ok, I'll try to pick up the various changes you've made regarding outputs by myself
I'm currently working on multi arch setup. Do you have any Raspberry device to test ? I've build multi arch images but I'm not able to test them : https://github.com/vanackej?tab=packages&repo_name=risco-mqtt-local

2022-07-04 16:33 UTC, markxroberts commented
Sorry, don't have a RPi to test.  Will try to look at reformatting the outputs changes to fit in with new structure if you like.    I'll work to update on a fork of your feature/support multiple panels code.

2022-07-04 21:11 UTC, vanackej commented
released in 0.5.0-beta.1

2022-07-04 21:11 UTC, closed without merging